### PR TITLE
quran submission

### PR DESCRIPTION
**Pull request by meysam-iran**
make sure to fix it

### CODE REVIEW

**Comment by meysam-iran** [comment]
WAKE UP JMKJJJGJFFJHGDHSDGFHRGVGFHGVBHV I CANT WAIT A 10 WHOLE YEARS JUST TO GET A REPLY

**Comment by meysam-iran** [comment]
@JoshAtticus sorry for mentioning but can you add this extension and fix it



i cant wait for 50 years

**Comment by meysam-iran** [comment]
@JoshAtticus wake up please

**Comment by JoshAtticus** [comment]
> @JoshAtticus wake up please

stop pinging me I don't have authority to merge this

**Comment by meysam-iran** [comment]
fine, this pull gets a UNPULL

**Pull request closed without merging**
