### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by JoshAtticus**
I spent hours on this

anyways it conflicts the new UI so you'll have to decide, mine or theirs

### CODE REVIEW

**Comment by CharcoalAfterlife** [comment]
Wow so cooly thingy

**Comment by cicerorph** [comment]
Gonna verify it

**Comment by CharcoalAfterlife** [comment]
yay thank you for doing that

**Comment by cicerorph** [comment]
Merged.

**Comment by CharcoalAfterlife** [comment]
> Merged.

Yyayayayayay thank you MubiLop

**Pull request merged**
